server:
  port: 8080
spring:
  application:
    name: fornecedores
  jpa:
  hibernate:
    ddl-auto: create
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: 'jdbc:postgresql://localhost:5432/db-fornecedores'
    username: postgres
    password: postgres
  sql:
    init:
      mode: always