apiVersion: v1
kind: Pod
metadata:
  name: db-fornecedores-pod
  labels:
    app: db-fornecedores-pod
spec:
  containers:
    - name: db-fornecedores-container
      image: postgres:12-alpine
      ports:
        - containerPort: 5432
      envFrom:
        - configMapRef:
            name: db-fornecedores-configmap
